### ISSUE TITLE
curiousapple - `createMarginTrading` of MarginTradingFactory wont work on actual mainnet

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#103]
curiousapple

medium

# `createMarginTrading` of MarginTradingFactory wont work on actual mainnet

## Summary
As stated here 
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L107
Dodo defines `createMarginTrading()` to allow users to create a margin trading account, deposit funds, and open a position.
However incorrect implementation of it won't allow the user to do so, **once it's deployed on the actual mainnet.** 

## Vulnerability Detail
There are three steps in `createMarginTrading()`.
**Step 1: Clone** :heavy_check_mark: 
**Step 2:  Deposit** :warning: 
Here if we look closely, dodo is always passing margin boolean as false for both types of deposits, hence these tokens are only transferred to the actual account, and `lendingPoolDeposit` is never done.
Hence there is no collateral in the name of the margin account in the lending pool yet.
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L144-L148

**Step 3: Open Trade** :negative_squared_cross_mark: 
The user passes rate mode as 1 or 2 in hopes of opening a position and incurring a debt.
However, since there is no collateral to borrow against, it would revert to Aave's side.
Stopping users from creating margin accounts.

The complete trace on aave's side is as per follows 
1. Flashloan (mode = 1,2)
https://github.com/aave/protocol-v2/blob/ce53c4a8c8620125063168620eba0a8a92854eb8/contracts/protocol/lendingpool/LendingPool.sol#L483
2. _executeBorrow
https://github.com/aave/protocol-v2/blob/ce53c4a8c8620125063168620eba0a8a92854eb8/contracts/protocol/lendingpool/LendingPool.sol#L540-L542
3. ValidationLogic.validateBorrow
https://github.com/aave/protocol-v2/blob/ce53c4a8c8620125063168620eba0a8a92854eb8/contracts/protocol/lendingpool/LendingPool.sol#L866
4. REVERT
https://github.com/aave/protocol-v2/blob/ce53c4a8c8620125063168620eba0a8a92854eb8/contracts/protocol/libraries/logic/ValidationLogic.sol#L168
`require(vars.userCollateralBalanceETH > 0, Errors.VL_COLLATERAL_BALANCE_IS_0);`

Whats interesting about this issue is, DODO do have a test to test this functionality, and expect it to work.
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/test/marginTrading/MarginTradingFactory.t.sol#L35
However this issue is missed in testing, since they are using mocked lending pool without verifcations on collateral.

## Impact
1. Breaks project assumptions.
Protocol mentions it clearly that they would like users to create, deposit, and open trade using the concerned function, but due to this issue, users can not. 
They have even written a test to confirm it but missed the validations in mocked setup.

2. Users being unaware would waste a significant amount of gas in failed calls to createMarginTrading()

## Code Snippet
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L115

## Tool used

Manual Review

## Recommendation
Consider passing margin boolean as true, so there is collateral to borrow against.
Also, consider adding forking mainnet to your test suite

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is not valid M. 
"dodo is always passing margin boolean as false for both types of deposits" is for test. 

1. `depositMarginTradingETH` internally converts msg.value to weth, which is no problem.
2. `_depositMarginTradingERC20` internally transfers erc20 from msg.sender to _marginTradingAddress via  `DODOApprove.claimTokens`. Before calling `createMarginTrading`, user must approve erc20 to DODOApprove. This is no problem.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Considering this a valid low based on the impact and above comments.
