### ISSUE TITLE
GimelSec - `MarginTrading.sol` can't be upgradable.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#152]
GimelSec

medium

# `MarginTrading.sol` can't be upgradable.

## Summary

`MarginTradingFactory` uses `Clones.cloneDeterministic` to create a new `MarginTrading` contract. However, `MarginTrading` seems to be an upgradeable contract.  But `Clone` is not compatible with upgradeable contracts. 

https://docs.openzeppelin.com/contracts/3.x/api/proxy
> The Clones library provides a way to deploy minimal non-upgradeable proxies for cheap. This can be useful for applications that require deploying many instances of the same contract (for example one per user, or one per task). These instances are designed to be both cheap to deploy, and cheap to call. The drawback being that they are not upgradeable.

## Vulnerability Detail

`MarginTradingFactory` uses `Clones.cloneDeterministic` to create a new `MarginTrading`.
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L121
```solidity
    function createMarginTrading(
        uint8 _flag,
        bytes calldata depositParams,
        bytes calldata executeParams
    ) external payable returns (address marginTrading) {
        if (_flag == 1) {
            marginTrading = Clones.cloneDeterministic(
                MARGIN_TRADING_TEMPLATE,
                keccak256(abi.encodePacked(msg.sender, crossMarginTrading[msg.sender].length, _flag))
            );
            …
    }
```

And `MarginTrading` seems to be an upgradeable contract.
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L19
```solidity
contract MarginTrading is OwnableUpgradeable, IMarginTrading, IFlashLoanReceiver {
```

The answer in this post explains why `Clone` is not compatible with upgradeable contracts. https://forum.openzeppelin.com/t/contract-factory-for-upgradeable-erc721/11153
> The problem is that the implementation address for the transparent proxy is kept in the storage of the transparent proxy, but when the user goes through the clone it will be using the storage of the clone, so it doesn’t know where to delegate.

## Impact

If MARGIN_TRADING_TEMPLATE is an upgradeable contract, `Clones.cloneDeterministic` only returns the address of the transparent proxy without the actual implementation.

## Code Snippet

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L121
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L129
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L19

## Tool used

Manual Review

## Recommendation

Don’t use an upgradeable contract as the implement address in `Clone`. If DODO want a upgradeability mechanism for `MarginTrading`, consider using [Beacon](https://docs.openzeppelin.com/contracts/3.x/api/proxy#beacon)

**Comment by securitygrid** [comment]
Escalate for 10 USDC
As stated by the sponsor, MarginTrading.sol has no upgrade requirements. Nothing bad will happen. It is a valid Low/Info.

**Comment by ctf-sec** [comment]
The report is written under the assumption that MarginTrading is upgradeable, while the sponsor clearly intend not to use a upgradeable contract,

can be a valid low

**Comment by sces60107** [comment]
Escalate for 10 USDC

Here to make a contra-argument of the above escalation.

First, I agree with the sponsor's comment that if the purpose of adding the OwnableUpgradeable contract was to facilitate the initialization of the owner through the init method, nothing bad happens. But the purpose wasn't stated during the contest.

Also, securitygrid and ctf-sec mentioned that the issue won't harm the protocol since the sponsor intend not to use a upgradeable contract. But I think roguereddwarf  has already made a clear contra-argument: 
> the additional information provided by the sponsor was not available at the time of the contest

Therefore, I think the assumption in this report is valid. And under the assumption the issue did harm the protocol. This issue should stay medium.

**Comment by securitygrid** [comment]
to @sces60107:
Please point out where the proxy is.

**Comment by abhishekvispute** [comment]
Escalate for 10 USDC 

Is there any place where DODO mentioned that these contracts are upgradeable?
The upgradable contract inheritance is done for the initialize support and having initialized is common practice in all clone proxy patterns, to not add the complexity of the constructor handling inside bytecode. 

For example 
https://github.com/nounsDAO/streamer/blob/781f7b8e1028e2ea0983b1c7c026149e4751861e/src/StreamFactory.sol#L211 

Hence the contract having `initialize` or inheriting an upgradable contract is not enough to draw the conclusion that the contract is designed to be upgradable.

**Comment by roguereddwarf** [comment]
With the additional information provided by @abhishekvispute my initial comment assuming "initializer = deployed behind a proxy" was a stretch.
It's probably fair to make this Low/Informational

**Comment by securitygrid** [comment]
@roguereddwarf
The same question I asked sces60107 is also for you:
**Please point out where the proxy is.**
This question is enough to show that it is not implemented in upgradeable way

**Comment by roguereddwarf** [comment]
@securitygrid I said I don't see the proxy so I think it's Low/Informational and not a valid H/M. I think you misunderstood my latest comment

**Comment by securitygrid** [comment]
@roguereddwarf I did not misunderstand you, ser. You think this question is invalid because you read abhishekvispute's escalatation. The question I raised was ignored. You seem to prefer to see long escalatations :)

**Comment by roguereddwarf** [comment]
Sry I didn't mean to ignore your question. I answered the other comment because it addressed a specific assumption I had made in my initial comment.
Also I'm not the judge, nor am I Sherlock staff. So I'm just giving my opinion here. The resolution of the escalations including your escalation is handled by Sherlock staff
