### ISSUE TITLE
roguereddwarf - MarginTrading.sol: When partially closing a trade all tokens are used to pay back debt and not only the swapped tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-dodo-judging#80]
roguereddwarf

medium

# MarginTrading.sol: When partially closing a trade all tokens are used to pay back debt and not only the swapped tokens

## Summary
It's expected by the protocol that funds can be in the `MarginTrading` contract without being used for anything.

We can see this by looking at the `MarginTradingFactory.depositMarginTradingETH` and `MarginTradingFactory.depositMarginTradingERC20` functions.

If the user sets `margin=false` as the parameter, the funds are only sent to the `MarginTrading` contract but NOT deposited into Aave.

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L203-L211

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L259-L272

The purpose of this is that the user can then call `lendingPoolDeposit` or `lendingPoolRepay` to add margin or close a trade.

When a trade is partially closed by taking out a flash loan and swapping it for the debt token all the funds are used to pay back debt but it should be restricted to the funds that were swapped.

## Vulnerability Detail
When partially closing a trade (`flag=0`) the `MarginTrading._closetrade` function is called and `_tradeAmounts` is set like this:

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L320-L323

So it's set to the full balance, and this amount is then used to repay the debt:

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L325-L327

So this does not leave those funds idle that were in the contract before.

## Impact
When partially closing a trade the amount that is repaid can be bigger than expected. So the funds that should remain in the contract for other purposes are used up and cannot be used otherwise.

Also since more debt is repaid than intended the trade is altered in an unintended way and will now be liquidated at a different price which is not what the user wants.

## Code Snippet
https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L203-L211

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTradingFactory.sol#L259-L272

https://github.com/sherlock-audit/2023-05-dodo/blob/main/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol#L294-L356

## Tool used
Manual Review

## Recommendation
Only use swapped funds to partially repay debt.

```diff
diff --git a/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol b/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol
index f68c1f3..29176f9 100644
--- a/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol
+++ b/dodo-margin-trading-contracts/contracts/marginTrading/MarginTrading.sol
@@ -318,8 +318,14 @@ contract MarginTrading is OwnableUpgradeable, IMarginTrading, IFlashLoanReceiver
                 _tradeAmounts[i] = (IERC20(_debtTokens[i]).balanceOf(address(this)));
             }
         } else {
+            int256[] memory _amountsBefore = new uint256[](_tradeAssets.length);
             for (uint256 i = 0; i < _tradeAssets.length; i++) {
-                _tradeAmounts[i] = (IERC20(_tradeAssets[i]).balanceOf(address(this)));
+                _amountsBefore[i] = IERC20(_tradeAssets[i]).balanceOf(address(this));
+            }
+            for (uint256 i = 0; i < _tradeAssets.length; i++) {
+                if (_tradeAmounts[i] > IERC20(_tradeAssets[i]).balanceOf(address(this))) {
+                    _tradeAmounts[i] = (IERC20(_tradeAssets[i]).balanceOf(address(this))) - _amountsBefore[i];
+                }
             }
         }
         for (uint256 i = 0; i < _tradeAssets.length; i++) {
```
Duplicate of #72

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is valid low/info as stated by the sponsor. No bad impact.

**Comment by ctf-sec** [comment]
the impact is

> When a trade is partially closed, the repayment amount may exceed expectations, depleting the funds intended for other uses within the contract and rendering them unusable. 

intend to maintain the severity level

**Comment by securitygrid** [comment]
Agreed. But I don't want to close it. Please let sherlock know my 5 questions.

**Comment by abhishekvispute** [comment]
Escalate for 10 USDC 

Request for Duplication

There is no clear definition anywhere that the margin account is supposed to hold the balance, the skip in a factory on its own is not enough to support it IMO.
I don't want to argue about the validity of this issue, it is ambiguous.
I leave that to you guys, however, if you consider it valid.

I think both https://github.com/sherlock-audit/2023-05-dodo-judging/issues/72 and this issue #80 should be considered as duplicates.
The cause for both issues is missing accounting between commitment and the balance of tokens for 2 different functions.

Consider that there is a random contract with two different functions 
```
openPosition()
IERC20(address).transfer

repay()
IERC20(address).transfer
```

Would you consider the issue of safe transfer for tokens like USDT differently for open-position and repayment, or consider them as duplicates?

In audits we used to do, we consider those as duplicates.
However, I don't know about Sherlock, if you don't, all okay :)

**Comment by roguereddwarf** [comment]
The notion of a separate balance can e.g. also be observed in the `MarginTrading.withdrawERC20` + `MarginTrading.withdrawETH` functions. You can pass a `margin` flag to indicate whether to withdraw the funds from the contract balance or from Aave.

I decided to report them separately because:
1) One affects opening a trade, the other affects closing a trade
2) The impact is different in terms of severity

I think it's possible to make them duplicates though with #72 being the primary one as the impact is worse there.

**Comment by ctf-sec** [comment]
Can consider this report duplicate of 72 and close this one

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #72
